### ISSUE TITLE
Port to WebExtensions

### ISSUE THREAD

**Issue by nt1m** [captnfab/FireTitle#12]
The API needed to change window titles is now supported.

**Comment by grahamperrin** [comment]
Mozilla bug [1333376 - Feature request: a WebExtension API to change the window title](https://bugzilla.mozilla.org/show_bug.cgi?id=1333376)

> RESOLVED FIXED in Firefox 56

**Comment by grahamperrin** [comment]
@captnfab I drew special attention to FireTitle at <https://discourse.mozilla.org/t/-/15451/12?u=grahamperrin>. Enjoy. I'm hugely grateful to the developers.

**Comment by captnfab** [comment]
Thanks! :)

**Comment by nt1m** [comment]
@captnfab Might be better if you update FireTitle instead of creating a new extension, so all your current users get upgraded to. For those who want to use the old one, they can look in the previous versions

**Comment by captnfab** [comment]
Indeed, that was my first choice.
However, the author of the original extension is not responding to my mails for years now.
Since I can't have full control over the extension because of someone missing in action, I figured I would be better to create another one.
But maybe mozilla.org have a way to deal with MIA people and give ownership rights to active devs… dunno... I'll ask about that.
