### ISSUE TITLE
Titles assigned to wrong windows after session restore

### ISSUE THREAD

**Issue by molexx** [captnfab/FireTitle#16]
For a clean test I created a new profile in FF Developer Edition 57.0b3 from aurora update channel.

Open three windows
In each window open a page you'll recognise - I just did google searches for 'window one', 'window two' and 'window three'
In each window open CrappyFireTab and set the title - I used 'win1', 'win2' and 'win3' - closing the plugin's config tab between each one otherwise pressing the toolbar button jumps to the already open one in the other window.
Quit Firefox.
Reopen firefox and press restore session. I've also tested by changing the settings to restore session by default.
The three windows appear, with their three google searches, but their CrappyFireTitle title seems to be randomly assigned.

**Comment by captnfab** [comment]
Thanks for your report, I'll investigate.

**Comment by captnfab** [comment]
Ok, I found the cause of the problem. When a session is restored, the windows are restored but their Id may changes.
So, storing window's names / title patterns using window's id can't work.

**Comment by rsalmei** [comment]
Hey! Thanks for the response in the mozilla review.
Just came here to vote for the issue. It should have a way to accomplish this... Good luck!

**Comment by Betlista** [comment]
FF 57.0 forced me to switch from FireTitle to Crappy and after FF restart (I have option "Show your windows and tabs from last time") all titles (except one) are gone :-(

**Comment by captnfab** [comment]
Yes. Windows naming on restore is broken. Any help is welcome.

**Comment by Betlista** [comment]
@captnfab Can you point me directly to part, in which it is storing/loading titles?

**Comment by captnfab** [comment]
Sure. The problem is actually pretty simple.
Here: https://github.com/captnfab/FireTitle/blob/106507e1e8bf9cd2755872ba4882018c5d0fc98d/firetitle/background.js#L8 window's pattern/name are saved in the local storage as win+windowId+_name/pattern. (saving part occurs here: https://github.com/captnfab/FireTitle/blob/106507e1e8bf9cd2755872ba4882018c5d0fc98d/firetitle/background.js#L48 )

Unfortunately, window's ids change upon restore. This means storing parameters that way can't work.
When I tried, the window.sessionId was a blank field, so it was unreliable too.

Hence, the problem is I don't know how to keep track of a window through session restoration…

**Comment by captnfab** [comment]
I think that the local storage is the wrong way to go.
Using sessions seems a much clearer approach: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/sessions

**Comment by captnfab** [comment]
Let me try to do something...

**Comment by Betlista** [comment]
I do not see the problem with local storage... The problem is a unique identifier. I see few candidates in https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/Tab id or sessionId, can you try tab.sessionId instead of window.sessionId ? I know that you are doing it on window level, maybe you can do something like save id/sessionId of a first tab in every window...

**Comment by captnfab** [comment]
I've got it working. I'm doing some cleaning since I'm not really proud of the state of the code.
I'm also polishing the UI.
I'll try to push the new version today and upload it to mozilla addons website for review.

**Comment by eceprof** [comment]
Captnfab, you are fabulous. I just "upgraded" to Firefox Quantum and to my dismay lost the ability to use FireTitle, felt saved by Crappy FireTitle and then discovered the session restore problem!!! Imagine my relief when I opened this page and discovered at the end of it that you have found a solution the very day I looked for one. Thank you so much for being a lifesaver. FireTitle is second only to session restore to being my most needed and loved FireFox extension/capability.

**Comment by captnfab** [comment]
I've uploaded the new version to addons.mozilla.org and it is now pending review.

**Comment by captnfab** [comment]
@eceprof hehe, thanks!
The addons.mozilla.org version has been approved. Please tell me if it works well for you :)

**Comment by Betlista** [comment]
I'm also going to test immediately ;-)

**Comment by Betlista** [comment]
Tested with 24 windows and 236 tabs and worked as expected, thanks for fix!
